# SPDX-License-Identifier: GPL-2.0
obj-y = mcontext.o \
         registers.o \
         signal.o \
         prctl.o \
         tls.o \
         uaccess.o

USER_OBJS := $(obj-y)

include $(srctree)/arch/um/scripts/Makefile.rules
